# Try to find the FREEGLUT library
#
# FREEGLUT_INCLUDE_DIR
# FREEGLUT_LIBRARY
# FREEGLUT_FOUND

#  ${CMAKE_INCLUDE_PATH}
#  ${OPENGL_INCLUDE_DIR}
#  /usr/include
#  /usr/local/include

#  ${CMAKE_LIBRARY_PATH}
#  /usr/lib
#  /usr/local/lib

FIND_PATH(
  GLUT_INCLUDE_DIR GL/freeglut.h
  /usr/local/opt/freeglut/include/
  NO_DEFAULT_PATH
)
FIND_LIBRARY(
  GLUT_LIBRARIES
  NAMES glut libglut
  PATHS
    /usr/local/opt/freeglut/lib/
  NO_DEFAULT_PATH
)

IF (GLUT_INCLUDE_DIR AND GLUT_LIBRARIES)
   SET(FREEGLUT_FOUND TRUE)
ENDIF ()

IF (FREEGLUT_FOUND)
   IF (NOT FREEGLUT_FIND_QUIETLY)
      MESSAGE(STATUS "Found FREEGLUT: ${GLUT_LIBRARIES}, ${GLUT_INCLUDE_DIR}")
   ENDIF (NOT FREEGLUT_FIND_QUIETLY)
ELSE (FREEGLUT_FOUND)
   IF (FREEGLUT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FREEGLUT")
   ENDIF (FREEGLUT_FIND_REQUIRED)
ENDIF (FREEGLUT_FOUND)
